#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Mar  9 15:30:39 2024

@author: jim
"""

import time
from  pyreadstat import read_sas7bdat
 

t = time.time()
df,meta = read_sas7bdat(fp)
elapsed = time.time() - t

